// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx4STNfzBwgvMjM6XbK-6x65Qa9BTpWjk',
    appId: '1:981562936510:web:398a8d5d11dfc95a27e2ef',
    messagingSenderId: '981562936510',
    projectId: 'ascs-dd799',
    authDomain: 'ascs-dd799.firebaseapp.com',
    databaseURL: 'https://ascs-dd799-default-rtdb.firebaseio.com',
    storageBucket: 'ascs-dd799.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2JZmeCbEdREwemceRr4DIY8AwDQQyYg8',
    appId: '1:981562936510:android:6b0e0c490cac25fc27e2ef',
    messagingSenderId: '981562936510',
    projectId: 'ascs-dd799',
    databaseURL: 'https://ascs-dd799-default-rtdb.firebaseio.com',
    storageBucket: 'ascs-dd799.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDESzlat5JX2vUlhD0zhjXlv3On4qdZYxE',
    appId: '1:981562936510:ios:4b2d6c4fcb27f91927e2ef',
    messagingSenderId: '981562936510',
    projectId: 'ascs-dd799',
    databaseURL: 'https://ascs-dd799-default-rtdb.firebaseio.com',
    storageBucket: 'ascs-dd799.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDESzlat5JX2vUlhD0zhjXlv3On4qdZYxE',
    appId: '1:981562936510:ios:4b2d6c4fcb27f91927e2ef',
    messagingSenderId: '981562936510',
    projectId: 'ascs-dd799',
    databaseURL: 'https://ascs-dd799-default-rtdb.firebaseio.com',
    storageBucket: 'ascs-dd799.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx4STNfzBwgvMjM6XbK-6x65Qa9BTpWjk',
    appId: '1:981562936510:web:1797fe1aec558a4827e2ef',
    messagingSenderId: '981562936510',
    projectId: 'ascs-dd799',
    authDomain: 'ascs-dd799.firebaseapp.com',
    databaseURL: 'https://ascs-dd799-default-rtdb.firebaseio.com',
    storageBucket: 'ascs-dd799.firebasestorage.app',
  );
}
