name: Flutter CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5" # Set your desired Flutter version

      # ✅ Add this step before flutter pub get
      - name: Create .env file
        run: |
          echo "API_URL=${{ secrets.API_URL }}" >> .env

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      # Optional: Build web app
      # - name: Build web
      #   run: flutter build web

      - name: Build APK
        run: flutter build apk
